"""
Read the 201 spreadsheet and report what will and will not import. Writes nothing.

    python3 scripts/import-201/audit.py "/path/to/EMPLOYEE'S DETAILS-PRESENT.xlsx"

Two outputs, deliberately different:

  * stdout — COUNTS ONLY. No name, number, address or birth date. Safe to paste
    into a chat, a ticket or a terminal someone is sharing.
  * audit-report.md — the full detail, every issue against the row and person it
    belongs to. Written beside the spreadsheet, never into the repo. This is the
    file to work from when correcting the sheet.

The split is the point. Deciding what to fix needs names; discussing the shape of
the problem does not, and the second should not drag the first along with it.
"""
import collections
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import read_sheet  # noqa: E402

# Ordered worst-first: an unreadable date loses information, an unmapped branch
# is a lookup someone can fill in.
SEVERITY = {
    'birth-year-disagrees': 'CHECK', 'age-disagrees': 'CHECK',
    'left-before-hired': 'CHECK', 'under-18': 'CHECK',
    'separated-without-a-last-day': 'CHECK',
    'stale-active-in-the-archive': 'CHECK',
    'separated-but-filed-under-active': 'CHECK',
    'date-unreadable': 'MANUAL', 'date-impossible': 'MANUAL',
    'branch-unmapped': 'MANUAL', 'status-unmapped': 'MANUAL',
    'status2-unmapped': 'MANUAL', 'education-unmapped': 'MANUAL',
    'height-impossible': 'MANUAL', 'weight-implausible': 'MANUAL',
    'phone-unreadable': 'DROPPED', 'email-unreadable': 'DROPPED',
    'height-unreadable': 'DROPPED', 'weight-unreadable': 'DROPPED',
    'id-has-no-digits': 'DROPPED', 'document-unmapped': 'DROPPED',
}
EXPLAIN = {
    'CHECK': 'imports, but two things in the sheet disagree — worth an eye',
    'MANUAL': 'imports without this field; needs entering by hand afterwards',
    'DROPPED': 'the cell was not a usable value; the words are kept in Remarks',
}


def main(path):
    people, issues, skipped = read_sheet.read(path)
    active = [p for p in people if p['isActive']]
    left = [p for p in people if not p['isActive']]

    print(f'read {len(people)} people from {os.path.basename(path)}')
    print(f'  active    {len(active)}')
    print(f'  separated {len(left)}')
    print(f'  skipped   {len(skipped)}')

    print('\nfield coverage (active people — the ones that matter now)')
    for field in ('dateHired', 'birthDate', 'branch', 'phone', 'address', 'gender',
                  'civilStatus', 'heightCm', 'weightGrams', 'educationLevel',
                  'email', 'sss', 'hdmf', 'philhealth', 'tin',
                  'emergencyName', 'emergencyContact', 'employmentType'):
        have = sum(1 for p in active if p.get(field) is not None)
        bar = '#' * round(20 * have / max(len(active), 1))
        print(f'  {field:<18} {have:>3}/{len(active):<3} {bar}')

    by_kind = collections.Counter(i.kind for i in issues)
    print('\nissues by kind (whole sheet)')
    for level in ('CHECK', 'MANUAL', 'DROPPED'):
        rows = [(k, n) for k, n in by_kind.most_common() if SEVERITY.get(k) == level]
        if not rows:
            continue
        print(f'  {level} — {EXPLAIN[level]}')
        for kind, n in rows:
            print(f'    {n:>4}  {kind}')

    active_rows = {p['row'] for p in active}
    hot = sum(1 for i in issues if i.row in active_rows)
    print(f'\nof those, {hot} fall on active people; {len(issues) - hot} on separated')

    out = os.path.join(os.path.dirname(os.path.abspath(path)), 'audit-report.md')
    _write_report(out, people, issues, skipped, active_rows)
    print(f'\nfull detail (with names) written to:\n  {out}')
    print('This file contains personal data — keep it out of the repo and off email.')


def _write_report(out, people, issues, skipped, active_rows):
    by_row = collections.defaultdict(list)
    for i in issues:
        by_row[i.row].append(i)
    who = {p['row']: p for p in people}

    with open(out, 'w', encoding='utf-8') as f:
        f.write('# 201 import — audit\n\n')
        f.write('Generated by `scripts/import-201/audit.py`. Nothing has been imported.\n')
        f.write('Fix what you want fixed in the spreadsheet, then run it again.\n\n')
        f.write('**This file contains personal data.** Do not commit it.\n\n')

        for heading, rows in (('Active people', sorted(r for r in by_row if r in active_rows)),
                              ('Separated people', sorted(r for r in by_row if r not in active_rows))):
            f.write(f'\n## {heading}\n\n')
            if not rows:
                f.write('Nothing to look at.\n')
                continue
            f.write('| Sheet row | Person | Column | What | Cell says |\n')
            f.write('|---|---|---|---|---|\n')
            for r in rows:
                p = who.get(r, {})
                name = ' '.join(x for x in (p.get('firstName'), p.get('lastName')) if x) or '(no name)'
                for i in sorted(by_row[r], key=lambda i: SEVERITY.get(i.kind, 'ZZ')):
                    cell = str(i.detail).replace('|', '\\|')[:80]
                    f.write(f'| {r} | {name} | {i.column} | '
                            f'{SEVERITY.get(i.kind, "?")}: {i.kind} | `{cell}` |\n')

        if skipped:
            f.write('\n## Rows not imported\n\n')
            for r, why in skipped:
                f.write(f'- row {r}: {why}\n')


if __name__ == '__main__':
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    main(sys.argv[1])
